### ISSUE TITLE
商品一覧ページ「/products」のデザイン

### ISSUE THREAD

**Issue by hiro4869** [hiro4869/shoesapp#26]
- [x] 商品一覧ページ「/products」のデザイン
  - [x] 画像が適切な大きさで配置されている
  - [x] 画像がいい感じに揃っている
  - [x] リンクの色を茶色等の雰囲気にする
  - [x] 商品名、価格、カテゴリー、ブランドが表示されている

**Comment by anrichan** [comment]
#26
